### ISSUE TITLE
test: cast multiple vote in same time

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/mana#122]
Currently we are not sure how Mana would react if we cast multiple vote in same time for SX-SN. We need to test this to make sure nonce management is working well and not get stuck so we don't get surprise when we release to public.

**Comment by Sekhmet** [comment]
It's possible to fail transactions with simultaneous voting right now:
https://testnet.starkscan.co/tx/0x23da3e5b2d0dba0a3cd8e1da9be6e631822ecd513a29f1d96f909be89609f2b
https://testnet.starkscan.co/tx/0x28237282745c88644c4e5bea07a3912ae04e6d8224199f3814748f767350edc
https://testnet.starkscan.co/tx/0x12a23684ca8298fcf5675337738bb4ac28217d6949bfcf5daa8234337f2970b

**Comment by bonustrack** [comment]
Ok that's not the prefered outcome, I can see txs have the same nonce. I believe we will need a queue system to we trigger a new tx only after we get a confirmation (or rejection) from previous tx

**Comment by Sekhmet** [comment]
I already looked at potential solutions and it seems it won't be simple to handle all edge cases (biggest issue is that transactions could fail even if we manage nonces correctly, and this can result in gaps potentially blocking transactions from showing up, we could rebroadcast those, but then txHash will change and UI will lose track of the transaction - but maybe we could live with this for now).
