### ISSUE TITLE
Query gas estimate for process block with Fossil

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/mana#74]
We should query for gas estimation for process block with Fossil here https://github.com/snapshot-labs/mana/blob/master/src/fossil.ts#L51-L69

We should also not use a multicall (as we only send a single tx)

**Comment by bonustrack** [comment]
This is taken by @0xPilot

**Comment by emanuel-sol** [comment]
Is this being worked on? I don't see a PR or any sign of life.

**Comment by zzuziak** [comment]
Hey @0xPilot, did you start working on the issue?
